name: Build and Attach VSCode Extension to Release

on:
  release:
    types:
      - created

jobs:
  build-and-upload:
    runs-on: ubuntu-latest

    steps:
      - name: Clean dependencies
        run: |
          rm -rf node_modules
          rm -f pnpm-lock.yaml

      - name: Checkout repository
        uses: actions/checkout@v3

      - uses: pnpm/action-setup@v4
        with:
          version: 9
          run_install: false

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: pnpm install

      - name: Install vsce
        run: pnpm install -g vsce

      - name: Build the extension
        run: pnpm run compile

      - name: Package the extension
        run: vsce package
        env:
          VSCODE_ACCESS_TOKEN: ${{ secrets.VSCODE_ACCESS_TOKEN }}

      - name: Upload extension artifact to release
        uses: softprops/action-gh-release@v1
        with:
          files: "*.vsix"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
